<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('bills', function (Blueprint $table) {
            $table->integer('serial')->nullable();
        });

        // 2. Fill existing rows
        DB::statement("
    WITH numbered AS (
        SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
        FROM bills
    )
    UPDATE bills
    SET serial = numbered.rn
    FROM numbered
    WHERE bills.id = numbered.id;
");

        // 3. Make it NOT NULL
        DB::statement("
    ALTER TABLE bills
    ALTER COLUMN serial SET NOT NULL
");

        // 4. Add identity
        DB::statement("
    ALTER TABLE bills
    ALTER COLUMN serial
    ADD GENERATED BY DEFAULT AS IDENTITY
");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('bills', function (Blueprint $table) {
            //
            $table->dropColumn('serial');
        });
    }
};
